# Generated by Django 4.1.13 on 2025-06-26 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(max_length=155, upload_to='')),
                ('name', models.CharField(max_length=155)),
                ('position', models.CharField(max_length=155)),
                ('exprience', models.IntegerField()),
                ('specialization', models.CharField(max_length=155)),
                ('language', models.CharField(max_length=155)),
                ('desc', models.TextField(max_length=9999)),
                ('email', models.CharField(max_length=155)),
                ('team', models.CharField(choices=[('Management', 'Management'), ('Agents', 'Agents')], default='Agents', max_length=155)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=155)),
                ('photo', models.FileField(max_length=155, upload_to='')),
                ('desc', models.TextField(max_length=9999)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_type', models.CharField(max_length=20)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_page_name', models.CharField(max_length=155)),
                ('description', models.TextField(max_length=1555)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comprassion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_type', models.CharField(max_length=155)),
                ('total_area', models.IntegerField()),
                ('starting_price_flat', models.IntegerField()),
                ('flat_images_models', models.FileField(max_length=155, upload_to='')),
                ('category', models.CharField(max_length=155)),
                ('unit_type', models.CharField(max_length=155)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(max_length=155, upload_to='')),
                ('module_type', models.CharField(choices=[('Property', 'Property'), ('OffPlan', 'OffPlan'), ('Blog', 'Blog')], max_length=155)),
                ('module_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=155)),
                ('photo', models.FileField(max_length=155, upload_to='')),
                ('desc', models.TextField(max_length=9999)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_images_name', models.CharField(max_length=155)),
                ('office_images', models.FileField(max_length=155, upload_to='')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OffPlaneProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=155)),
                ('locations', models.CharField(max_length=155)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('starting_price', models.CharField(default=0, max_length=155)),
                ('starting_area', models.CharField(default=0, max_length=155)),
                ('handover', models.CharField(blank=True, max_length=155, null=True)),
                ('description', models.TextField(blank=True, max_length=9999, null=True)),
                ('location_description', models.CharField(blank=True, max_length=9999, null=True)),
                ('price_valid', models.CharField(blank=True, max_length=155, null=True)),
                ('total_number_flat', models.CharField(blank=True, max_length=155, null=True)),
                ('status_of_project', models.CharField(blank=True, max_length=155, null=True)),
                ('units', models.CharField(blank=True, max_length=155, null=True)),
                ('developer', models.CharField(blank=True, max_length=155, null=True)),
                ('payment_plan', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners_name', models.CharField(max_length=155)),
                ('partners_images', models.FileField(max_length=155, upload_to='')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PopularArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=155)),
                ('price_from', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_project_text', models.TextField(max_length=1555)),
                ('our_project_images', models.FileField(max_length=155, upload_to='')),
                ('heading', models.CharField(default='NEW HOME FOR GENRATIONS', max_length=155)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1555)),
                ('property_location', models.CharField(max_length=155)),
                ('property_type', models.CharField(choices=[('Apartments', 'Apartments'), ('villa', 'villa'), ('Penthouses', 'Penthouses'), ('Townhouses', 'Townhouses'), ('Duplexes', 'Duplexes'), ('Plots', 'Plots'), ('Offices', 'Offices')], max_length=155)),
                ('total_area', models.IntegerField()),
                ('bedroom', models.IntegerField(choices=[(1, '1'), (2, '2 '), (3, '3'), (4, '4'), (5, '5'), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')], max_length=155)),
                ('bathroom', models.IntegerField(default=0, max_length=155)),
                ('rate', models.IntegerField()),
                ('rent', models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=155)),
                ('desc', models.TextField(default='...', max_length=15555)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('indoor', models.CharField(blank=True, max_length=100, null=True)),
                ('outdoor', models.CharField(blank=True, max_length=100, null=True)),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('display_images', models.FileField(blank=True, null=True, upload_to='display/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), sm.models.validate_image])),
                ('assign_agents', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='sm.agents')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('photo', models.FileField(default=False, max_length=155, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), sm.models.validate_image])),
                ('property_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='sm.property')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persentage_installment', models.CharField(max_length=1555)),
                ('payment_year', models.CharField(max_length=1555)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('flat_plan_id', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sm.flatplan')),
                ('off_plane_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='sm.offplaneproperties')),
            ],
        ),
        migrations.AddField(
            model_name='flatplan',
            name='off_plane_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='sm.offplaneproperties'),
        ),
    ]
