# Generated by Django 4.1.13 on 2025-06-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='exprience',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flatplan',
            name='starting_price_flat',
            field=models.IntegerField(max_length=155),
        ),
        migrations.AlterField(
            model_name='flatplan',
            name='total_area',
            field=models.IntegerField(max_length=155),
        ),
        migrations.AlterField(
            model_name='imagesmodule',
            name='module_id',
            field=models.IntegerField(max_length=155),
        ),
        migrations.AlterField(
            model_name='populararea',
            name='price_from',
            field=models.IntegerField(max_length=155),
        ),
        migrations.AlterField(
            model_name='property',
            name='rate',
            field=models.IntegerField(max_length=155),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.IntegerField(max_length=155),
        ),
    ]
