# Generated by Django 4.1.13 on 2025-06-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0002_alter_agents_exprience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='exprience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flatplan',
            name='starting_price_flat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flatplan',
            name='total_area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='imagesmodule',
            name='module_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='populararea',
            name='price_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(choices=[(1, '1'), (2, '2 '), (3, '3'), (4, '4'), (5, '5'), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.IntegerField(),
        ),
    ]
