# Generated by Django 4.1.13 on 2025-07-18 19:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import sm.models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0003_alter_agents_exprience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offplaneproperties',
            name='images',
        ),
        migrations.AddField(
            model_name='offplaneproperties',
            name='display_images',
            field=models.FileField(blank=True, null=True, upload_to='display/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), sm.models.validate_image]),
        ),
        migrations.AddField(
            model_name='offplaneproperties',
            name='property_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Apartments', 'Apartments'), ('villa', 'villa'), ('Penthouses', 'Penthouses'), ('Townhouses', 'Townhouses'), ('Duplexes', 'Duplexes'), ('Plots', 'Plots'), ('Offices', 'Offices')], default='Plots', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OffPlanePropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), sm.models.validate_image])),
                ('property_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='sm.offplaneproperties')),
            ],
        ),
    ]
